#! /bin/sh

wmname LG3D
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width        2
bspc config window_gap          2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a jetbrains-studio desktop='^3' state=floating follow=on
bspc rule -a discord desktop='^3' follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
